package org.example.UI.TutoriaUI;

import org.example.Model.Tutoria;
import org.example.Util.Listar.ListsContainer;

import javax.swing.table.DefaultTableModel;
import java.util.List;

public class MostrarListaTutoria extends javax.swing.JInternalFrame {

    private String encabezados[] = {"Id", "Fecha", "Hora", "Duracion", "Comentarios", "Alumno Id"};
    private DefaultTableModel modelo = new DefaultTableModel();


    /**
     * Creates new form MostrarListaProfesores
     */
    public MostrarListaTutoria() {
        initComponents();
        modelo.setColumnIdentifiers(encabezados);
        this.jTable1.setModel(modelo);
        cargarDatosTabla(ListsContainer.obtenerListaTutorias());

    }

    public void cargarDatosTabla(List<Tutoria> lista){
        for (Tutoria t: lista){
            modelo.addRow(new Object[]{
                    t.getId(),t.getFecha(), t.getHora(), t.getDuracion(), t.getComentarios(),t.getAlumno_id()
            });
        }
    }

    /*
    public void llenarTabla(List<Profesor> profesores){
         for(Profesor x: profesores){
             modelo.addRow(new Object[]{
                x.getId(), x.getNombre(), x.getApellidos(),
                 x.getCorreo(), x.getAnioIngreso(), x.getGradoAcademico(),x.getAdscripcion()
            });
         }
    }
    */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Tabla de Tutorias");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}

