package org.example.UI.AlumnoUI;

import org.example.Model.Alumno;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class MostrarListaAlumnos extends javax.swing.JInternalFrame {

    private String encabezados[] = {"Id", "Nombre", "Apellidos", "Matricula ", "Correo", "Telefono de casa",
            "Telefono Celular", "Fecha de nacimiento", "Año de ingreso", "Carrera", "Su Tutor"};
    private DefaultTableModel modelo = new DefaultTableModel();


    /**
     * Creates new form MostrarListaProfesores
     */
    public MostrarListaAlumnos() {
        initComponents();
        modelo.setColumnIdentifiers(encabezados);
        this.jTable1.setModel(modelo);
        //llenarTabla(listar());
        cargarDatosTabla(generarListaAlumnos());
    }

    public void cargarDatosTabla(List<Alumno> alumnos){
        for(Alumno a: alumnos){
            modelo.addRow(new Object[]{
                    a.getId(), a.getNombre(), a.getApellidos(), a.getMatricula(), a.getCorreo(), a.getTelefonoCasa(),
                    a.getTelefonoCelular(), a.getFechaNacimiento(), a.getAnioIngreso(), a.getCarrera(), a.getTutorId()
            });
        }
    }

    public  List<Alumno> generarListaAlumnos(){
        //public Alumno(String id, String matricula, String nombre, String apellidos, String correo, String telefonoCasa, String telefonoCelular, String fechaNacimiento, String anioIngreso, String carrera, String tutorId) {
        List<Alumno> alumnos = new ArrayList();
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        alumnos.add( new Alumno("1","3322j", "Jose", "Rivera", "Email", "+3322", "+0324","9/11/2001", "2020","IC", "Domingo"));
        return alumnos;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Tabla de alumnos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}

