package org.example.UI.AlumnoUI;

import org.example.Model.Alumno;
import org.example.Model.Profesor;
import org.example.Respositorios.RepositorioAlumno;
import org.example.SuperFuncion.SuperFuncion;
import org.example.Util.AlumnoIdGeneration.AlumnoIdGeneration;
import org.example.Util.Listar.ListsContainer;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

public class RegistrarAlumno extends javax.swing.JInternalFrame {
    String carreras[] = {
            "Ingenieria en computacion",
            "Zootecnia", "Ingenieria Agricola"};

    private String id;
    private String matricula;
    private String nombre;
    private String apellidos;
    private String correo;
    private String telefonoCasa;
    private String telefonoCelular;
    private String fechaNacimiento;
    private String anioIngreso;
    private String carrera;
    private String tutorId;

    /**
     * Creates new form RegistrarAlumno
     */
    public RegistrarAlumno() {
        initComponents();
        agregarItemCarrera(carreras);
        agregarItemTutor(obtenerListaItem(ListsContainer.obtenerListaProfesoresTutores()));
    }

    public List<String> obtenerListaItem(List<Profesor> p){
        List<String> lista = new ArrayList<>();
        for (Profesor t: p ) {
            lista.add(t.getId());
        }
        return lista;
    }

    public void agregarItemCarrera(String s[]){
        for(String x: s){
            boxCarrera.addItem(x);
        }
    }

    public void agregarItemTutor (List<String> t){
        for(String s: t){
            boxTutor.addItem(s);
        }
    }

    public void cargarDatosCajaTexto(){
        nombre = txtNombre.getText();
        apellidos = txtApellidos.getText();
        correo = txtCorreo.getText();
        matricula = txtMatricula.getText();
        telefonoCasa = txtTelCasa.getText();
        telefonoCelular = txtTelCel.getText();
        fechaNacimiento = txtFechaNacim.getText();
        anioIngreso = txtIngreso.getText();
        carrera = this.boxCarrera.getSelectedItem().toString();
        tutorId = boxTutor.getSelectedItem().toString();
    }

    public boolean validarCamposVacios(){
        return !nombre.isEmpty() && !apellidos.isEmpty() && !correo.isEmpty() && !matricula.isEmpty()
                && !telefonoCasa.isEmpty() && !telefonoCelular.isEmpty() && !fechaNacimiento.isEmpty()
                && !anioIngreso.isEmpty() && !carrera.isEmpty() && !tutorId.isEmpty();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelCasa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelCel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaNacim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIngreso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        boxTutor = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        boxCarrera = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Alumno");

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Correo");

        jLabel4.setText("Matricula");

        jLabel5.setText("Telefono de casa");

        jLabel6.setText("Telefono Celular");

        jLabel7.setText("Fecha de nacimiento");

        jLabel8.setText("Año de ingreso");

        jLabel9.setText("Carrera");

        jLabel10.setText("Tutor");

        jButton1.setText("Registrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addComponent(jLabel3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(txtNombre)
                                                                        .addComponent(txtCorreo)
                                                                        .addComponent(txtTelCasa)
                                                                        .addComponent(txtFechaNacim)
                                                                        .addComponent(boxCarrera, 0, 238, Short.MAX_VALUE))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(37, 37, 37)
                                                                .addComponent(jLabel8))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel10)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(txtApellidos)
                                                                                .addComponent(txtMatricula)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(txtTelCel)
                                                                                .addComponent(txtIngreso)
                                                                                .addComponent(boxTutor, 0, 313, Short.MAX_VALUE))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel9))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(169, 169, 169)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTelCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtFechaNacim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(boxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(boxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        cargarDatosCajaTexto();
        if(validarCamposVacios()){
            //Todo Agregar el registro a la base de datos
            Alumno alumno = new Alumno();
            alumno.setNombre(nombre);
            alumno.setApellidos(apellidos);
            alumno.setCorreo(correo);
            alumno.setMatricula(matricula);
            alumno.setTelefonoCelular(telefonoCelular);
            alumno.setTelefonoCasa(telefonoCasa);
            alumno.setFechaNacimiento(fechaNacimiento);
            alumno.setAnioIngreso(anioIngreso);
            alumno.setCarrera(carrera);
            alumno.setTutorId(tutorId);
            alumno.setId(AlumnoIdGeneration.generateIdAlumno(matricula,anioIngreso));
            if(SuperFuncion.crear(new RepositorioAlumno(), alumno)){
                JOptionPane.showMessageDialog(null, "Se Registro al Alumno");
            } else {
                JOptionPane.showMessageDialog(null, "No se registro al alumno");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Hay datos vacios en el formulario");
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> boxCarrera;
    private javax.swing.JComboBox<String> boxTutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacim;
    private javax.swing.JTextField txtIngreso;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelCasa;
    private javax.swing.JTextField txtTelCel;
    // End of variables declaration
}

