package org.example.UI.TutorUI;

import org.example.Model.Profesor;
import org.example.Util.Listar.ListsContainer;

import javax.swing.table.DefaultTableModel;
import java.util.List;

public class MostrarTutores extends javax.swing.JInternalFrame {
    String [] encabezado = {"Id", "Nombre","Correo", "Carrera"};
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form MostrarTutores
     */
    public MostrarTutores() {
        initComponents();
        modelo.setColumnIdentifiers(encabezado);
        this.jTable1.setModel(modelo);
        cargarDatosTutoresTabla(ListsContainer.obtenerListaProfesoresTutores());
    }

    public void cargarDatosTutoresTabla(List<Profesor> profesores){
        for(Profesor a: profesores){
            modelo.addRow(new Object[]{
                    a.getId(), a.getNombre(), a.getCorreo(), a.getCorreo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tutores");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration
}

